### ISSUE TITLE
Example code fails - Failure to open files

### ISSUE THREAD

**Issue by dshkol** [teamookla/ooklaOpenDataR#13] opened 2020-12-01 06:59 UTC
Hello, thanks for putting together and releasing this package. 

I installed successfully and attempted to run the example code:
```
remotes::install_github("teamookla/ooklaOpenDataR")
library(ooklaOpenDataR)
get_performance_tiles(service = "mobile", quarter = 3, year = 2020)
```
This returned an error:
```
Downloading data from 's3://ookla-open-data/parquet/performance/type=mobile/year=2020/quarter=3/2020-07-01_performance_mobile_tiles.parquet'...
Error in io___MemoryMappedFile__Open(path, mode) : 
  IOError: Failed to open local file 's3://ookla-open-data/parquet/performance/type=mobile/year=2020/quarter=3/2020-07-01_performance_mobile_tiles.parquet'. Detail: [errno 2] No such file or directory
```
Also checked with:
```
arrow::read_parquet('s3://ookla-open-data/parquet/performance/type=mobile/year=2020/quarter=3/2020-07-01_performance_mobile_tiles.parquet')
Error in io___MemoryMappedFile__Open(path, mode) : 
  IOError: Failed to open local file 's3://ookla-open-data/parquet/performance/type=mobile/year=2020/quarter=3/2020-07-01_performance_mobile_tiles.parquet'. Detail: [errno 2] No such file or directory
```

Has the source bucket been removed or changed at all?

**Comment by katiejolly-ookla** [comment] 2020-12-01 14:50
Thanks for letting us know! I'm looking into this now. The source bucket hasn't changed so it looks like this is a code issue. If you need data more quickly, you can use [these URLs](https://github.com/teamookla/ookla-open-data#download-via-url) and fill in the parameters of interest (quarter, year, etc.)

**Comment by dshkol** [comment] 2020-12-02 01:35
> Thanks for letting us know! I'm looking into this now. The source bucket hasn't changed so it looks like this is a code issue. If you need data more quickly, you can use [these URLs](https://github.com/teamookla/ookla-open-data#download-via-url) and fill in the parameters of interest (quarter, year, etc.)

Thanks for taking a look. The links do work just fine. I imagine it may also be an issue on my end, or perhaps a missing import in the code, but all required packages are installed, and I checked through the source code and looked alright to me.

**Comment by ghost** [comment] 2020-12-03 16:50
@dshkol I haven't been able to reproduce this, but we'll keep trying. Have you received this error multiple times?

Also, do you use AWS or S3 for other purposes? It seems possible that you may have it configured differently than we do, and it'd be good to make this package more robust to things like that.

**Comment by dshkol** [comment] 2020-12-04 00:51
@bdcookla I've found the source of the error. My system had an outdated installation of the `arrow` package. Updating it from cran resolved the issue; however, I'm surprised it even happened as you have a minimum version requirement `arrow (>= 2.0.0),` in your desc file. Feel free to close, but I'm curious why install succeeded despite the wrong version of arrow.

**Comment by ghost** [comment] 2020-12-04 01:10
@dshkol interesting! That seems strange to me as well. I'm glad you resolved it, at least.

I'll close this issue, but please feel free to let us know if you run into any other issues (or have suggestions).

**Closed as completed by ghost** 2020-12-04 01:10 UTC
